### ISSUE TITLE
Refresh Probleme Listing

### ISSUE THREAD

**Issue by TRXMaik** [CTJaeger/DExchange#1]
<img width="373" alt="refresh" src="https://user-images.githubusercontent.com/47918413/53286574-12ef1000-3771-11e9-84cb-0d0dfb2dd16e.png">
Verkaufte Token werden nicht refreshed.
Candy wurde im gezeigten Screenshot zu 100% verkauft, wird aber noch komplett angezeigt.

**Comment by TRXMaik** [comment]
Damit zusammenhängend kann ich weiterhin mit der Prozentangabe auf den Amount zugreifen, beim Verkaufen, wenn auch nicht den Verkauf ausführen.

**Comment by CTJaeger** [comment]
Issue is fixed. Next upcoming Version.
