### ISSUE TITLE
BUG: defect main window showing

### ISSUE THREAD

**Issue by TRXMaik** [CTJaeger/DExchange#12]
Betreff Version 1.0.0.149

![bug4-terc-dex](https://user-images.githubusercontent.com/47918413/53304465-d0fbc200-3875-11e9-8f08-689a3ff90e65.png)

Siehe Punkte 1 - 3 im Screenshot.

1.  Favoriten werden im nicht maximierten Fenster nicht angezeigt, sind versteckt
2. das Limit-Fenster für offene Aufträge ist nicht der Größe des Fensters angepasst
3. die Buttons sind alle verschoben

**Comment by CTJaeger** [comment]
Fixed
