### ISSUE TITLE
BUG: favorites not shown after resize

### ISSUE THREAD

**Issue by TRXMaik** [CTJaeger/DExchange#18]
Wird das Programm auf Vollbild umgestellt und wieder auf die kleine Ursprungsgöße zurück, werden die Favoriten nicht mehr angezeigt, die Spalte verschwindet in der Anzeige.
Programmversion: .151

![bug10-terc-dex](https://user-images.githubusercontent.com/47918413/53347291-0efdf200-3919-11e9-95fd-1a4a6b626a62.png)

**Comment by CTJaeger** [comment]
Fixed
