### ISSUE TITLE
BUG: Update announce Pop-up

### ISSUE THREAD

**Issue by TRXMaik** [CTJaeger/DExchange#19]
![bug9-terc-dex](https://user-images.githubusercontent.com/47918413/53347339-26d57600-3919-11e9-8c09-dc80dc20e2f7.png)

Das Announce pop-up wurde mehrmals geladen und angezeigt.
Führt man nun das Update mit Klick auf das vorderste Pop-up aus und startet am Ende das Programm mit der entsprechenden Meldung neu, so wird auch das Programm so oft geöffnet, wie die Pop-ups vorher erschienen sind.

**Comment by TRXMaik** [comment]
Zusätzlich zeigt das Pop-up nicht die korrekte neue verfügbare Version an, sondern die gleiche, wie die die installiert ist.

**Comment by CTJaeger** [comment]
Fixed
