### ISSUE TITLE
BUG: Exchange TRC10

### ISSUE THREAD

**Issue by TRXMaik** [CTJaeger/DExchange#25]
![bug12-terc-dex](https://user-images.githubusercontent.com/47918413/53667229-b0b27580-3c70-11e9-94c7-9047daac1a8d.png)
Das Anzeigefeld für die Walletaddresse ist zu kurz, womit sich die korrekte Adresse nicht verifizieren lässt.

**Comment by CTJaeger** [comment]
Fixed
