### ISSUE TITLE
BUG: partial limit order sell

### ISSUE THREAD

**Issue by TRXMaik** [CTJaeger/DExchange#27]
Szenario:
Kauf und Verkauf von TERC in kleinen Batches wurden jeweils zu 100% ausgeführt und funktionierten einwandfrei.
46 SEED wurden auf einem Wallet deponiert und sollten zu einem Betrag x verkauft werden.
1. Preis x als Limit-Order gesetzt / komplette Menge
2. Preis x wurde nach einiger Zeit erreicht und wurde in zwei Teilen teilweise verkauft
--> Fehler tritt auf

BUG 1:
1. gemäß angezeigter verkaufter Order wurden 2 x 6 SEED verkauft = 12 SEED
2. bei den offenen Aufträgen werden noch 13 offene SEED angezeigt
--> 2 x 6 = 12 --> 46 - 12 |= 13 
hier wird falsch berechnet/angezeigt

auf dem Screenshot von TronWalletme wird dagegen die korrekte verkaufte Menge angezeigt:
2 x 15 = 30 --> 46 - 30 |= 13

Nach einem Neustart der Applikation wird die korrekte Menge von 16 SEED angezeigt, die nicht verkauft wurde.

--> BUG 2:
Nach der Falschberechnung werden keine Orders mehr ausgeführt, weder kaufen noch verkaufen, auch wenn die Targets unter- bzw. überschritten werden.
Der Fehler lässt sich nur durch einen Neustart der Applikation beheben.

![bug13a-terc-dex](https://user-images.githubusercontent.com/47918413/53763968-5ada0980-3ecc-11e9-896d-eb87e4b3b794.png)

![screenshot_20190304-204048](https://user-images.githubusercontent.com/47918413/53763977-62011780-3ecc-11e9-86fa-22a72de3948d.jpg)

**Comment by CTJaeger** [comment]
Fixed
