### ISSUE TITLE
Request: transactions.csv save path

### ISSUE THREAD

**Issue by TRXMaik** [CTJaeger/DExchange#31]
Einstellmöglichkeit des Pfades als zu exportierende Datei.
Momentan wird die Datei nur im versteckten Userprofil gespeichert, wird aber nirgends zur Auswahl angeboten.

**Comment by CTJaeger** [comment]
Under Config / Tradelog since the very first version adjustable.

**Comment by TRXMaik** [comment]
Das ist nur halb korrekt.
1. Unter "config" wird weiterhin "/report.csv" angegeben, obwohl die Datei "transactions.csv" heißt
2. Es gibt keine Möglichkeit den Pfad des Speicherns auszuwählen, was mit diesem Request gewünscht wurde.
Niemand will sich hinsetzen und aus dem Dateiexplorer den Pfad in das Programm kopieren. ;-)
