### ISSUE TITLE
Request: csv export

### ISSUE THREAD

**Issue by TRXMaik** [CTJaeger/DExchange#5]
Es wäre praktisch und auch für spätere steuerliche Abrechnungen hilfreich, wenn alle Transaktionen exportiert werden können.
Hierbei bietet sich das relativ Format unabhängige csv an.
Als Delimiter empfehle ich ";".
Ein Beispiel ist anbei (txt im Namen einfach entfernen).
[TERCDex csv export idea - Sheet1.csv.txt](https://github.com/CTJaeger/DExchange/files/2896936/TERCDex.csv.export.idea.-.Sheet1.csv.txt)

Diese Reihenfolge ist als Vorschlag anzusehen und kann durch andere Interessierte gern kommentiert, erweitert und angepasst werden.

**Comment by TRXMaik** [comment]
Da es nicht direkt aus der Tron Blockchain kommt, nur zusätzlich:
Da der Preis für TRX in der Dex angezeigt wird, ist er ja bekannt.
Ggf. könnte man den zu dem Zeitpunkt gülitigen Wert in einer extra Spalte festhalten.

**Comment by CTJaeger** [comment]
Done.
