### ISSUE TITLE
Request: Save Limit Orders

### ISSUE THREAD

**Issue by TRXMaik** [CTJaeger/DExchange#6]
Beim Schließen des Programms werden alle geplanten Limit Orders gelöscht, so dass beim Neustart und Login alle geplanten Aufträge nicht länger vorhanden sind.

Vorschlag:
Speichern der geplanten Aufträge und automatischer Import der letzten Session beim Login.
Ggf. als Option einbauen, so dass jeder selbst entscheiden kann, ob dies gewünscht ist.
Könnte man im Konfigurationsfenster mit unterbringen.

**Comment by CTJaeger** [comment]
Done.
