### ISSUE TITLE
BUG: Frozen + TotalValue + Total overview

### ISSUE THREAD

**Issue by TRXMaik** [CTJaeger/DExchange#8]
![bug2-terc-dex](https://user-images.githubusercontent.com/47918413/53296196-a163a000-380a-11e9-8c43-c26a206fc4e2.png)
Bei der Anzeige gibt es zwei Fehler:
1. Bei [Frozen] wird die Gesamtanzahl eines willkürlichen Wallets aus dem Adressbuch angezeigt
2. auf Grundlage des ersten Fehlers, wird der [TotalValue] falsch ausgegeben

3. unabhängig von dieser Situation, wird niemals das [Total] ausgegeben, es sind immer 0.00 USDT
4. Zwischen [TRX Balance], [Tokenbalance], [Frozen], [TotalVaulue] sowie [Total] und dem Wert fehlt ein Leerzeichen, welches bei [TRX] der Ordnung halber exisitert

**Comment by CTJaeger** [comment]
1. fixed
2. fixed
3. okay
4. fixed
