### ISSUE TITLE
BUG: Token overview

### ISSUE THREAD

**Issue by TRXMaik** [CTJaeger/DExchange#9]
![bug3-terc-dex](https://user-images.githubusercontent.com/47918413/53296317-48e1d200-380d-11e9-9452-257d065142c1.png)
Die Anzeige der Tokenanzahl im Tokenoverview wird inkorrekt, sobald eine Adresse im [Address Book] eingetragen wird.

Alle Werte werden aus einem beliebigen hinzugefügten Konto entnommen und angezeigt, während beim Validieren der Version des Programms auf das eigentliche Wallet zugegriffen wird und der entsprechende TERC-Wert ausgelesen und angezeigt wird.

**Comment by CTJaeger** [comment]
Fixed.
